### ISSUE TITLE
Move extension code into addon/ directory

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#270]

**Comment by fzzzy** [comment]
When I try to do this, I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/cfx", line 33, in <module>
    cuddlefish.run()
  File "/usr/local/Cellar/mozilla-addon-sdk/1.17/libexec/python-lib/cuddlefish/__init__.py", line 753, in run
    abort_on_missing=options.abort_on_missing)
  File "/usr/local/Cellar/mozilla-addon-sdk/1.17/libexec/python-lib/cuddlefish/manifest.py", line 669, in build_manifest
    mxt.build(scan_tests, test_filter_re)
  File "/usr/local/Cellar/mozilla-addon-sdk/1.17/libexec/python-lib/cuddlefish/manifest.py", line 203, in build
    self.datamaps[self.target_cfg.name] = DataMap(self.target_cfg)
  File "/usr/local/Cellar/mozilla-addon-sdk/1.17/libexec/python-lib/cuddlefish/manifest.py", line 145, in __init__
    datamap[dataname] = hash_file(absname)
  File "/usr/local/Cellar/mozilla-addon-sdk/1.17/libexec/python-lib/cuddlefish/manifest.py", line 120, in hash_file
    return hashlib.sha256(open(fn,"rb").read()).hexdigest()
IOError: [Errno 2] No such file or directory: '/Users/donovan/code/pageshot/client/data/interface.css'
```

Even though the file ```/Users/donovan/code/pageshot/client/data/interface.css``` exists.

**Comment by ianb** [comment]
Some files are symlinked (in this case from the appengine/ directory), so moving them around leaves dangling symlinks.  I think we'll still need to symlink between the server and the addon, but we'll just have to fix any.  `interface.css` is the only one I see at the moment.

**Comment by fzzzy** [comment]
Great, thanks.

**Comment by fzzzy** [comment]
At this point, since the file is in the appengine directory, which is going away, I'm just going to move the interface.css file into the extension. We can file another bug to unify styles between client and server in the future.
