### ISSUE TITLE
Error message when database is unavailable is not clear

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#280]
This is the error message I get when I just run gulp and forget about the database:

```
GET /data/1428609678021/xxx {}
Error in Model.get: { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
GET /meta/1428609678021/xxx {}
Error in Model.get: { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

This specific error should get caught and turned into an error like "Database unavailable on {connection string}"

**Comment by ianb** [comment]
I notice when I give a bad connection string, it acts like it all worked: `creating tables on postgres://ianbicking@localhost:5431/ianbicking`

(that being a bad port number)

Another error comes out when there's not a database connection:

```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /Users/ianbicking/src/pageshot/server/dist/models.js:166:41
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

probably an attempt to do `JSON.parse('undefined')`
