### ISSUE TITLE
Occasional duplicate key error

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#613]
I get this error sometimes locally:

```
PUT /data/7aQ2wMbv/news.ycombinator.com 200 727.871 ms - 14
Error: Error saving Object:
error: duplicate key value violates unique constraint "data_pkey"

error: duplicate key value violates unique constraint "data_pkey"
    at [object Object].Connection.parseE (/Users/ianbicking/src/pageshot/node_modules/pg/lib/connection.js:534:11)
    at [object Object].Connection.parseMessage (/Users/ianbicking/src/pageshot/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/ianbicking/src/pageshot/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20) error: duplicate key value violates unique constraint "data_pkey" { [error: duplicate key value violates unique constraint "data_pkey"]
  name: 'error',
  length: 198,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key (id)=(7aQ2wMbv/news.ycombinator.com) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'data',
  column: undefined,
  dataType: undefined,
  constraint: 'data_pkey',
  file: 'nbtinsert.c',
  line: '406',
  routine: '_bt_check_unique' }
```

I don't know why this happens.  There does seem to be a key with that id in the database.  But then it should update, no?

**Comment by ianb** [comment]
Could be a race?

**Comment by ianb** [comment]
There used to be a `.catch()` in servershot.js (around line 110), that would check for error 23505 and return false.
