### ISSUE TITLE
Error in shot index

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#661]
I get this error on http://pageshot.dev.mozaws.net/shots

```
General error:
Error: Empty deviceId: undefined

Error: Empty deviceId: undefined
    at Function.Shot.getShotsForDevice (/home/ubuntu/pageshot/dist/server/servershot.js:296:11)
    at /home/ubuntu/pageshot/dist/server/server.js:256:8
    at Layer.handle [as handle_request] (/home/ubuntu/pageshot/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/ubuntu/pageshot/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/ubuntu/pageshot/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/ubuntu/pageshot/node_modules/express/lib/router/layer.js:82:5)
    at /home/ubuntu/pageshot/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/home/ubuntu/pageshot/node_modules/express/lib/router/index.js:321:12)
    at next (/home/ubuntu/pageshot/node_modules/express/lib/router/index.js:261:10)
    at /home/ubuntu/pageshot/dist/server/server.js:76:3
```

**Comment by ianb** [comment]
This is because the cookies are sent over https, and if you access this over http then the cookie is not sent.  https-only would fix this, but just redirecting this page to https would also do enough.  We have to be sure we don't redirect development to https (where there is no https), so probably some configuration is needed to indicate if https is available.

**Comment by ianb** [comment]
We could put in an nginx redirect

**Comment by fzzzy** [comment]
if ($http_x_forwarded_proto != "https") {
                rewrite ^(.*)$ https://$server_name$1 permanent;
        }

Added to /etc/nginx/sites-enabled/default in both the pageshotcontent and pageshot sections.

**Comment by fzzzy** [comment]
Reverted, seemed to cause some problems

**Comment by fzzzy** [comment]
Ok, now the following causes only the shots page to be redirected. It is inside the pageshot block, below location / { ... }

        location /shots {
                if ($http_x_forwarded_proto != "https") {
                        rewrite ^(.*)$ https://$server_name$1 permanent;
                }
                proxy_pass http://127.0.0.1:10080;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $aws_scheme;
        }
